version: '3.8'

services:
  backup-sentinel:
    build: .
    volumes:
      - ./backup_storage:/backups  # Standardized path
      - ./config:/config           # For RBAC and encryption keys
    environment:
      - BACKUP_DIR=/backups
      - USERS_FILE=/config/users.json
      - KEY_FILE=/config/encryption.key
      # Optional cloud settings (uncomment when needed):
      # - S3_ENABLED=true
      # - S3_BUCKET=your-bucket
      # - AWS_ACCESS_KEY_ID=your-key
      # - AWS_SECRET_ACCESS_KEY=your-secret
    command: ["/data", "--compress", "zip"]  # Default command
